routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/gallery', 'GalleryController@index')->name('gallery');
Route::get('/gallery/{id}', 'GalleryController@show')->name('gallery');
Route::get('admin', 'adminPanel@index')->name('gallery');
Route::get('events', 'HomeController@events')->name('event');
Route::get('about-us', 'HomeController@about')->name('event');
Route::get('contact-us', 'HomeController@contact')->name('event');


Route::resource('artist', 'ArtistController');
Route::resource('event', 'EventController');
Route::resource('art', 'ArtController');

resources/views/dashboard.blade.php
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Dashboard</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <button class="btn btn-sm btn-outline-secondary">Share</button>
      <button class="btn btn-sm btn-outline-secondary">Export</button>
    </div>
    <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
      <span data-feather="calendar"></span>
      This week
    </button>
  </div>
</div>

<canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

<h2>Section title</h2>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1,001</td>
        <td>Lorem</td>
        <td>ipsum</td>
        <td>dolor</td>
        <td>sit</td>
      </tr>
      <tr>
        <td>1,002</td>
        <td>amet</td>
        <td>consectetur</td>
        <td>adipiscing</td>
        <td>elit</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>Integer</td>
        <td>nec</td>
        <td>odio</td>
        <td>Praesent</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>libero</td>
        <td>Sed</td>
        <td>cursus</td>
        <td>ante</td>
      </tr>
      <tr>
        <td>1,004</td>
        <td>dapibus</td>
        <td>diam</td>
        <td>Sed</td>
        <td>nisi</td>
      </tr>
      <tr>
        <td>1,005</td>
        <td>Nulla</td>
        <td>quis</td>
        <td>sem</td>
        <td>at</td>
      </tr>
      <tr>
        <td>1,006</td>
        <td>nibh</td>
        <td>elementum</td>
        <td>imperdiet</td>
        <td>Duis</td>
      </tr>
      <tr>
        <td>1,007</td>
        <td>sagittis</td>
        <td>ipsum</td>
        <td>Praesent</td>
        <td>mauris</td>
      </tr>
      <tr>
        <td>1,008</td>
        <td>Fusce</td>
        <td>nec</td>
        <td>tellus</td>
        <td>sed</td>
      </tr>
      <tr>
        <td>1,009</td>
        <td>augue</td>
        <td>semper</td>
        <td>porta</td>
        <td>Mauris</td>
      </tr>
      <tr>
        <td>1,010</td>
        <td>massa</td>
        <td>Vestibulum</td>
        <td>lacinia</td>
        <td>arcu</td>
      </tr>
      <tr>
        <td>1,011</td>
        <td>eget</td>
        <td>nulla</td>
        <td>Class</td>
        <td>aptent</td>
      </tr>
      <tr>
        <td>1,012</td>
        <td>taciti</td>
        <td>sociosqu</td>
        <td>ad</td>
        <td>litora</td>
      </tr>
      <tr>
        <td>1,013</td>
        <td>torquent</td>
        <td>per</td>
        <td>conubia</td>
        <td>nostra</td>
      </tr>
      <tr>
        <td>1,014</td>
        <td>per</td>
        <td>inceptos</td>
        <td>himenaeos</td>
        <td>Curabitur</td>
      </tr>
      <tr>
        <td>1,015</td>
        <td>sodales</td>
        <td>ligula</td>
        <td>in</td>
        <td>libero</td>
      </tr>
    </tbody>
  </table>
</div>

resources/views/gallery.blade.php
@extends('layouts.app')

@section('content')
<div class="container">


      @foreach ($arts as $item)
    <div class="card" style="width: 18rem;display: inline-block; margin-left:10px; margin-bottom: 20px;">
    <img src="/images/gallery/{{$item->photo}}" class="card-img-top" alt="{{$item->title}}">
      <div class="card-body">
      <h5 class="card-title">{{$item->title}}</h5>
      <h6 class="card-subtitle mb-2 text-muted"><span class="bold">By:</span> {{$item->artist->name}}</h6>
        <a href="{{ route('art.show',$item->id)}}" class="btn btn-primary" style="display:inline-block;">View</a>
        
      </div>
    </div>
  @endforeach
</div>
@endsection

resources/views/gallery_details.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    
        <h3 style="font-size: 1.3em;color: #047bde;font-weight: 500;">Title:</h3>
        <p >{{$art->title}}</p>
    
        <h3 style="font-size: 1.3em;color: #047bde;font-weight: 500;">By:</h3>
        {{-- <p >{{$art->artist->name}}</p> --}}
        <h3 style="font-size: 1.3em;color: #047bde;font-weight: 500;">Photo:</h3>
    <img src="/images/gallery/{{$art->photo}}" alt="{{$art->title}}">
        <h3 style="font-size: 1.3em;color: #047bde;font-weight: 500;">Description:</h3>
        <p style="white-space: pre-line">{{$art->description}}</p>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
    <h1>HOME PAGE</h1>
    </div>
</div>
@endsection