routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/gallery', 'GalleryController@index')->name('gallery');
Route::get('/gallery/{id}', 'GalleryController@show')->name('gallery');
Route::get('admin', 'adminPanel@index')->name('gallery');
Route::get('events', 'HomeController@events')->name('event');
Route::get('about-us', 'HomeController@about')->name('event');
Route::get('contact-us', 'HomeController@contact')->name('event');


Route::resource('artist', 'ArtistController');
Route::resource('event', 'EventController');
Route::resource('art', 'ArtController');

app/Artist.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Artist extends Model
{
    protected $fillable = [
        'name',
        'phone',
        'email',
        'gender',
        'age',
        'pic'       
    ];
    protected $table="artists";

    public function arts()
    {
        return $this->hasMany('App\Art');
    }
}

app/Http/Controllers/ArtistController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Artist;

class ArtistController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $artists = Artist::all();
        return view('artist.list', compact('artists'));
    }

    public function create() {
        return view('artist.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'phone'=>'required',
            'email'=>'required',
            'gender'=>'required',
            'pic'=>'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048'
        ]);
         $imagename=null;   
         
         if ($request->hasFile('pic')) {
            $imagePath = $request->file('pic');
            $imageName = time() . '.' . $imagePath ->getClientOriginalExtension();

            $imagePath->move('images/artists', $imageName );
            $imagename=$imageName;
        };
        $artist = new Artist([
            'name' => $request->get('name'),
            'phone' => $request->get('phone'),
            'email' => $request->get('email'),
            'gender' => $request->get('gender'),
            'age' => $request->get('age'),
            'pic' => $imagename
        ]);
        // echo $imagename;
        // print_r($artist); exit;
        $artist->save();
        return redirect('/artist')->with('success', 'Artist saved!');   
    }

    public function show($id)
    {
        
    }

    public function edit($id)
    {
        $artist = Artist::find($id);
        return view('artist.edit', compact('artist')); 
    }

    public function update(Request $request, $id)
    {
        
        $request->validate([
            'name'=>'required',
            'phone'=>'required',
            'email'=>'required',
            'gender'=>'required',
        ]);

        $artist = Artist::find($id);
        $artist->name =  $request->get('name');
        $artist->email = $request->get('email');
        $artist->phone = $request->get('phone');
        $artist->gender = $request->get('gender');
        $artist->age = $request->get('age');
        
        if ($request->hasFile('pic')) {
            $imagePath = $request->file('pic');
            $imageName = time() . '.' . $imagePath ->getClientOriginalExtension();

            $imagePath->move('images/artists', $imageName );
            $artist->pic=$imageName;
        };

        $artist->save();

        return redirect('/artist')->with('success', 'artist updated successfully!');
    }

    public function destroy($id)
    {
        $artist = Artist::find($id);
        $artist->delete();

        return redirect('/artist')->with('success', 'artist deleted successfully!');
    }
}

resources/views/artist/create.blade.php
@extends('layouts.admin')

@section('content')
   
<div class="row" style="margin-top:30px">
    <div class="col-sm-8 offset-sm-2">
       <h2 class="display-5">Add new Artist</h2>
       <hr>
     <div>
       @if ($errors->any())
         <div class="alert alert-danger">
           <ul>
               @foreach ($errors->all() as $error)
                 <li>{{ $error }}</li>
               @endforeach
           </ul>
         </div><br />
       @endif
         <form method="post" action="{{ route('artist.store') }}" enctype="multipart/form-data">
             @csrf
             <div class="form-group">    
                 <label for="name">Name:</label>
                 <input type="text" class="form-control" name="name" placeholder="Name"/>
             </div>
   
             <div class="form-group">
                 <label for="phone">Phone:</label>
                 <input type="text" class="form-control" name="phone" placeholder="Phone"/>
             </div>
   
             <div class="form-group">
                 <label for="email">Email:</label>
                 <input type="text" class="form-control" name="email" placeholder="Email"/>
             </div>
             <div class="form-group">
                 <label for="gender">Gender:</label>
                 <select name="gender" id="gender" class="form-control" >
                     <option value="">Select an Item</option>
                     <option value="male">Male</option>
                     <option value="female">Female</option>
                 </select>
             </div>
             <div class="form-group">
                <label for="email">Age:</label>
                <input type="number" min="10" max="100" class="form-control" name="age" placeholder="Age"/>
            </div>
             <div class="form-group">
                 <label for="country">Picture:</label>
                 <input type="file" name="pic" id="pic">
             </div>
                               
             <button type="submit" class="btn btn-success float-right">Add Artist</button>
         </form>
     </div>
   </div>
   </div>

@endsection

resources/views/artist/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update an Artist</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('artist.update', $artist->id) }}" enctype="multipart/form-data">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name" value={{ $artist->name }} />
            </div>

            <div class="form-group">
                <label for="phone">Phone:</label>
                <input type="number" class="form-control" name="phone" value={{ $artist->phone }} />
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" class="form-control" name="email" value={{ $artist->email }} />
            </div>
            <div class="form-group">
                <label for="gender">Gender:</label>
                <select name="gender" id="gender" class="form-control" value={{$artist->gender}} >
                    <option value="">Select an Item</option>
                    <option value="male" {{($artist->gender =='male') ? 'selected' : ''}}>Male</option>
                    <option value="female" selected={{($artist->gender =='female') ? 'selected' : ''}}>Female</option>
                </select>
            </div>
            <div class="form-group">
               <label for="email">Age:</label>
            <input type="number" min="10" max="100" class="form-control" name="age" placeholder="Age" value="{{$artist->age}}"/>
           </div>
            <div class="form-group">
                <label for="country">Picture:</label>
                <input type="file" name="pic" id="pic">
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/artist/list.blade.php
@extends('layouts.admin')

@section('content')
<h2>Artist List
  <span>
    <a href="{{ route('artist.create')}}" class="btn btn-primary float-right" style="display:inline-block;">Add new Artist</a>
  </span>
</h2>
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
<div class="table-responsive">
  <table class="table table-striped table-sm" style="text-align:center; line-height:100px">
    <thead>
      <tr>
        <th>Picture</th>
        <th>Name</th>
        <th>Email</th>
        <th>Gender</th>
        <th>Phone</th>
        <th>age</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        @foreach($artists as $artist)
      <tr>
        <td>
          @if ($artist->pic)
        <img src="images/artists/{{$artist->pic}}" class="rounded-circle" width="100" height="100" alt="" src="">
          @endif
          
        </td>
        <td>{{$artist->name}}</td>
        <td>{{$artist->email}}</td>
        <td>{{$artist->gender}}</td>
        <td>{{$artist->phone}}</td>
        <td>{{$artist->age}}</td>
        
        <td>
            
            <a href="{{ route('artist.edit',$artist->id)}}" class="btn btn-primary" style="display:inline-block;">Edit</a>

            <form action="{{ route('artist.destroy', $artist->id)}}" method="post" style="display:inline-block;">
              @csrf
              @method('DELETE')
              <button class="btn btn-danger" type="submit">Delete</button>
            </form>
        </td>
      </tr>

      @endforeach
    </tbody>
  </table>
</div>    
@endsection