routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/gallery', 'GalleryController@index')->name('gallery');
Route::get('/gallery/{id}', 'GalleryController@show')->name('gallery');
Route::get('admin', 'adminPanel@index')->name('gallery');
Route::get('events', 'HomeController@events')->name('event');
Route::get('about-us', 'HomeController@about')->name('event');
Route::get('contact-us', 'HomeController@contact')->name('event');


Route::resource('artist', 'ArtistController');
Route::resource('event', 'EventController');
Route::resource('art', 'ArtController');

app/Art.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Artist;

class Art extends Model
{
    protected $fillable = [
        "title",
        "category",
        "price", 
        "description",
        "artist_id",
        "photo"
    ];

    public function artist()
    {
        return $this->belongsTo(Artist::class);
    }
}

app/Http/Controllers/ArtController.php
<?php

namespace App\Http\Controllers;
use App\Artist;
use App\Art;
use Illuminate\Http\Request;

class ArtController extends Controller
{
    
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $arts = Art::with(['artist:name,id'])->paginate(10);
        return view('art.list', compact('arts'));
    }

    public function create() {
        $artists = Artist::all();
        return view('art.create',compact(['artists']));
    }

    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required',
            'category'=>'required',
            'price'=>'required',
            'description'=>'required',
            'artist_id'=>'required',
            'photo'=>'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
         $imagename=null;   
         
         if ($request->hasFile('photo')) {
            $imagePath = $request->file('photo');
            $imageName = time() . '.' . $imagePath ->getClientOriginalExtension();

            $imagePath->move('images/gallery', $imageName );
            $imagename=$imageName;
        };
        $art = new Art([
            'title' => $request->get('title'),
            'category' => $request->get('category'),
            'price' => $request->get('price'),
            'description' => $request->get('description'),
            'artist_id' => $request->get('artist_id'),
            'photo' => $imagename
        ]);
        $art->save();
        return redirect('/art')->with('success', 'New photo saved successfully!');  
    }

    public function show(Art $art)
    {
        $art= $art->load('artist:name,id');
        return view('art.show', compact('art'));
    }   

    public function destroy($id)
    {
        $art = Art::find($id);
        $art->delete();
        return redirect('/art')->with('success', 'art deleted successfully!');
    }
}

resources/views/art/create.blade.php
@extends('layouts.admin')

@section('content')
   
<div class="row" style="margin-top:30px">
    <div class="col-sm-8 offset-sm-2">
       <h2 class="display-5">Add new Photo</h2>
       <hr>
     <div>
       @if ($errors->any())
         <div class="alert alert-danger">
           <ul>
               @foreach ($errors->all() as $error)
                 <li>{{ $error }}</li>
               @endforeach
           </ul>
         </div><br />
       @endif
         <form method="post" action="{{ route('art.store') }}" enctype="multipart/form-data">
             @csrf
             <div class="form-group">    
                 <label for="title">Title:</label>
                 <input type="text" class="form-control" name="title" placeholder="Title"/>
             </div>
   
             <div class="form-group">
                 <label for="category">Category:</label>
                 <select name="category" id="category" class="form-control" >
                  <option value="oil-painting">Oil Painting</option>
                  <option value="Sketches">Sketches</option>
                  <option value="Digital arts">Digital arts</option>
                  <option value="Calligraphy">Calligraphy</option>
                  <option value="Photography">Photography</option>
                  <option value="Handicrafts">Handicrafts</option>
              </select>
             </div>
   
             <div class="form-group">
                 <label for="price">Price: AFN</label>
                 <input type="number" class="form-control" name="price" placeholder="price"/>
             </div>
             <div class="form-group">
                 <label for="artist_id">Artist:</label>
                 <select name="artist_id" id="artist_id" class="form-control" >
                   @if ($artists)
                   
                    @foreach ($artists as $artist)
                      <option value={{$artist->id}}>{{$artist->name}}</option>
                    @endforeach
                   @endif
                 </select>
             </div>
             <div class="form-group">
                 <label for="photo">photo:</label>
                 <input type="file" name="photo" id="photo">
             </div>
             <div class="form-group">
                <label for="email">Description:</label>
                <textarea name="description"class="form-control" id="description" cols="30" rows="10"></textarea>
            </div>
            
                               
             <button type="submit" class="btn btn-success float-right">Add Photo</button>
         </form>
     </div>
   </div>
   </div>

@endsection

resources/views/art/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update an Artist</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('artist.update', $artist->id) }}" enctype="multipart/form-data">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name" value={{ $artist->name }} />
            </div>

            <div class="form-group">
                <label for="phone">Phone:</label>
                <input type="number" class="form-control" name="phone" value={{ $artist->phone }} />
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" class="form-control" name="email" value={{ $artist->email }} />
            </div>
            <div class="form-group">
                <label for="gender">Gender:</label>
                <select name="gender" id="gender" class="form-control" value={{$artist->gender}} >
                    <option value="">Select an Item</option>
                    <option value="male" {{($artist->gender =='male') ? 'selected' : ''}}>Male</option>
                    <option value="female" selected={{($artist->gender =='female') ? 'selected' : ''}}>Female</option>
                </select>
            </div>
            <div class="form-group">
               <label for="email">Age:</label>
            <input type="number" min="10" max="100" class="form-control" name="age" placeholder="Age" value="{{$artist->age}}"/>
           </div>
            <div class="form-group">
                <label for="country">Picture:</label>
                <input type="file" name="pic" id="pic">
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/art/list.blade.php
@extends('layouts.admin')

@section('content')
<h2>Art List
  <span>
    <a href="{{ route('art.create')}}" class="btn btn-primary float-right" style="display:inline-block;">Add new Photo</a>
  </span>
</h2>
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
<div class="table-responsive">
  @foreach ($arts as $item)
    <div class="card" style="width: 18rem;display: inline-block; margin-left:10px; margin-bottom: 20px;">
    <img src="/images/gallery/{{$item->photo}}" class="card-img-top" alt="{{$item->title}}">
      <div class="card-body">
      <h5 class="card-title">{{$item->title}}</h5>
      <h6 class="card-subtitle mb-2 text-muted"><span class="bold">By:</span> {{$item->artist->name}}</h6>
        <a href="{{ route('art.show',$item->id)}}" class="btn btn-primary" style="display:inline-block;">View</a>
        <form action="{{ route('art.destroy', $item->id)}}" method="post" style="display:inline-block;">
          @csrf
          @method('DELETE')
          <button class="btn btn-danger" type="submit">Delete</button>
        </form>
      </div>
    </div>
  @endforeach
</div>    
@endsection

resources/views/art/show.blade.php
@extends('layouts.admin')

@section('content')
<h2>Photo Details
    <span>
        <a href="{{ route('art.index')}}" class="btn btn-primary float-right" style="display:inline-block;">Back</a>
      </span>
  </h2>
  <hr>
    <h3 style="font-size: 1.3em;color: #047bde;font-weight: 500;">Title:</h3>
    <p >{{$art->title}}</p>

    <h3 style="font-size: 1.3em;color: #047bde;font-weight: 500;">By:</h3>
    <p >{{$art->artist->name}}</p>
    <h3 style="font-size: 1.3em;color: #047bde;font-weight: 500;">Photo:</h3>
<img src="/images/gallery/{{$art->photo}}" alt="{{$art->title}}">
    <h3 style="font-size: 1.3em;color: #047bde;font-weight: 500;">Description:</h3>
    <p style="white-space: pre-line">{{$art->description}}</p>
@endsection