routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/gallery', 'GalleryController@index')->name('gallery');
Route::get('/gallery/{id}', 'GalleryController@show')->name('gallery');
Route::get('admin', 'adminPanel@index')->name('gallery');
Route::get('events', 'HomeController@events')->name('event');
Route::get('about-us', 'HomeController@about')->name('event');
Route::get('contact-us', 'HomeController@contact')->name('event');


Route::resource('artist', 'ArtistController');
Route::resource('event', 'EventController');
Route::resource('art', 'ArtController');

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = [
        'title',
        'location',
        'event_date',
        'description',     
    ];
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Event;

class EventController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $events = Event::all();
        return view('event.list', compact('events'));
    }

    public function create() {
        return view('event.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required',
            'location'=>'required',
            'event_date'=>'required',
            'description'=>'required'
        ]);
        
        $event = new Event([
            'title' => $request->get('title'),
            'location' => $request->get('location'),
            'event_date' => $request->get('event_date'),
            'description' => $request->get('description'),
        ]);
        
        $event->save();
        return redirect('/event')->with('success', 'event saved!');   
    }

    public function edit($id)
    {
        $event = Event::find($id);
        return view('event.edit', compact('event')); 
    }

    public function show($id)
    {
        $event = Event::find($id);
        return view('event.show', compact('event'));
    }

    public function update(Request $request, $id)
    {
        
        $request->validate([
            'title'=>'required',
            'location'=>'required',
            'event_date'=>'required',
            'description'=>'required'
        ]);

        $event = Event::find($id);
        $event->title =  $request->get('title');
        $event->location = $request->get('location');
        $event->event_date = $request->get('event_date');
        $event->description = $request->get('description');
        
        $event->save();

        return redirect('/event')->with('success', 'event updated successfully!');
    }

    public function destroy($id)
    {
        $event = Event::find($id);
        $event->delete();

        return redirect('/event')->with('success', 'event deleted successfully!');
    }

    public function website() {
        $events = Event::all();
        return view('event.website', compact('events'));
    }
}

resources/views/event/create.blade.php
@extends('layouts.admin')

@section('content')
   
<div class="row" style="margin-top:30px">
    <div class="col-sm-8 offset-sm-2">
       <h2 class="display-5">Add new Event</h2>
       <hr>
     <div>
       @if ($errors->any())
         <div class="alert alert-danger">
           <ul>
               @foreach ($errors->all() as $error)
                 <li>{{ $error }}</li>
               @endforeach
           </ul>
         </div><br />
       @endif
         <form method="post" action="{{ route('event.store') }}" enctype="multipart/form-data">
             @csrf
             <div class="form-group">    
                 <label for="title">Title:</label>
                 <input type="text" class="form-control" name="title" placeholder="Title"/>
             </div>
   
             <div class="form-group">
                 <label for="location">Location:</label>
                 <input type="text" class="form-control" name="location" placeholder="location"/>
             </div>
   
             <div class="form-group">
                 <label for="email">Date:</label>
                 <input type="date" class="form-control" name="event_date" placeholder="Event Date"/>
             </div>
             <div class="form-group">
              <label for="email">Description:</label>
              <textarea name="description"class="form-control" id="description" cols="30" rows="10"></textarea>
          </div>
          
                               
             <button type="submit" class="btn btn-success float-right">Add Event</button>
         </form>
     </div>
   </div>
   </div>

@endsection

resources/views/event/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update an Event</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('event.update', $event->id) }}" >
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="title">Title:</label>
                <input type="text" class="form-control" name="title" value={{ $event->title }} />
            </div>

            <div class="form-group">
                <label for="location">Location:</label>
                <input type="text" class="form-control" name="location" value="{{ $event->location }}" />
            </div>
            <div class="form-group">
                <label for="event_date">Date:</label>
                <input type="date" class="form-control" name="event_date" value={{ $event->event_date }} />
            </div>
            <div class="form-group">
                <label for="email">Description:</label>
                <textarea name="description"class="form-control" id="description" cols="30" rows="10">{{ $event->description }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/event/list.blade.php
@extends('layouts.admin')

@section('content')
<h2>Event List
  <span>
    <a href="{{ route('event.create')}}" class="btn btn-primary float-right" style="display:inline-block;">Add new Event</a>
  </span>
</h2>


<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
<div class="table-responsive">
  <table class="table table-striped table-sm" style="text-align:center;">
    <thead>
      <tr>
        <th>Title</th>
        <th>Location</th>
        <th>Event Date</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        @foreach($events as $event)
      <tr>
        <td>{{$event->title}}</td>
        <td>{{$event->location}}</td>
        <td>{{$event->event_date}}</td>
        <td>
            <a href="{{ route('event.edit',$event->id)}}" class="btn btn-primary" style="display:inline-block;">Edit</a>
            <a href="{{ route('event.show',$event->id)}}" class="btn btn-primary" style="display:inline-block;">View</a>
            <form action="{{ route('event.destroy', $event->id)}}" method="post" style="display:inline-block;">
              @csrf
              @method('DELETE')
              <button class="btn btn-danger" type="submit">Delete</button>
            </form>
        </td>
      </tr>

      @endforeach
    </tbody>
  </table>
</div>    
@endsection

resources/views/event/show.blade.php
@extends('layouts.admin')

@section('content')
<h2>Event Details
    <span>
        <a href="{{ route('event.index')}}" class="btn btn-primary float-right" style="display:inline-block;">Back</a>
      </span>
  </h2>
  <hr>
    <h3 style="font-size: 1.3em;color: #047bde;font-weight: 500;">Title:</h3>
    <p >{{$event->title}}</p>

    <h3 style="font-size: 1.3em;color: #047bde;font-weight: 500;">Location:</h3>
    <p >{{$event->location}}</p>
    <h3 style="font-size: 1.3em;color: #047bde;font-weight: 500;">Date:</h3>
    <p >{{$event->event_date}}</p>
    <h3 style="font-size: 1.3em;color: #047bde;font-weight: 500;">Description:</h3>
    <p style="white-space: pre-line">{{$event->description}}</p>
@endsection

resources/views/event/website.blade.php
<div class="row ">
    <div class="col-md-6 grid-margin-md stretch-card d-flex_">
        <div class="card">
          <div class="card-body">
            <div class="d-flex justify-content-between mb-3">
                <h4 class="card-title">Switch to Direct Plans</h4>
                <h6><a href="#" class="text-primary">See 4 More</a></h6>
            </div>
            <div class="border p-3 mb-3">
              <div class="border-bottom pb-3">
                <div class="row">
                    <div class="col-sm-4 border-right-lg border-right-md-0">
                      <div class="d-flex justify-content-center align-items-center">
                        <h1 class="mb-0 mr-2 text-primary font-weight-normal">04</h1>
                          <div>
                            <p class="font-weight-bold mb-0 text-dark">Feb</p>
                            <p class="mb-0">2018</p>
                          </div>
                      </div>
                    </div>
                    <div class="col-sm-8 pl-3">
                      <p class="text-dark font-weight-bold mb-0">Lorem ipsum dolor sit amit</p>
                      <p class="mb-0">9.30 PM - 10:30 PM</p>
                    </div>
                  </div>
              </div>
              <div class="pt-3">
                  <div class="row">
                      <div class="col-sm-4 border-right-lg border-right-md-0">
                        <div class="d-flex justify-content-center align-items-center">
                          <h1 class="mb-0 mr-2 text-primary font-weight-normal">15</h1>
                            <div>
                              <p class="font-weight-bold mb-0 text-dark">Mar</p>
                              <p class="mb-0">2018</p>
                            </div>
                        </div>
                      </div>
                      <div class="col-sm-8 pl-3">
                        <p class="text-dark font-weight-bold mb-0">Lorem ipsum dolor sit amit</p>
                        <p class="mb-0">10.00 PM - 12:30 PM</p>
                      </div>
                    </div>
                </div>
            </div>
            <div class="border p-3">
              <div class="border-bottom pb-3">
                <div class="row">
                    <div class="col-sm-4 border-right-lg border-right-md-0">
                      <div class="d-flex justify-content-center align-items-center">
                        <h1 class="mb-0 mr-2 text-primary font-weight-normal">22</h1>
                          <div>
                            <p class="font-weight-bold mb-0 text-dark">Apr</p>
                            <p class="mb-0">2018</p>
                          </div>
                      </div>
                    </div>
                    <div class="col-sm-8 pl-3">
                      <p class="text-dark font-weight-bold mb-0">Lorem ipsum dolor sit amit</p>
                      <p class="mb-0">9.30 PM - 10:30 PM</p>
                    </div>
                  </div>
              </div>
              <div class="pt-3">
                  <div class="row">
                      <div class="col-sm-4 border-right-lg border-right-md-0">
                        <div class="d-flex justify-content-center align-items-center">
                          <h1 class="mb-0 mr-2 text-primary font-weight-normal">26</h1>
                            <div>
                              <p class="font-weight-bold mb-0 text-dark">Jun</p>
                              <p class="mb-0">2018</p>
                            </div>
                        </div>
                      </div>
                      <div class="col-sm-8 pl-3">
                        <p class="text-dark font-weight-bold mb-0">Lorem ipsum dolor sit amit</p>
                        <p class="mb-0">10.00 PM - 12:30 PM</p>
                      </div>
                    </div>
                </div>
            </div>
          </div>
        </div>
    </div>
  </div>